@startuml
skinparam dpi 150
User -right-> Storage : acessa
Storage -right-> EC2 : requisições HTTP
EC2 -down-> RDS : conecta
User : Usuário
Storage : Site Estático (Object Storage / CDN)
EC2 : API Flask (EC2)
RDS : PostgreSQL RDS
@enduml